run:
  deadline: 5m
  skip-files:
   - ".*generated.*\\.go"
   - external/
   - controllers/virtualmachineservice/v1alpha1/utils/
   - controllers/virtualmachineservice/v1alpha2/utils/

# override defaults
linters-settings:
  # gocyclo:
  #   min-complexity: 18
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/vmware-tanzu
  importas:
    alias:
      - pkg: k8s.io/api/core/v1
        alias: corev1
      - pkg: github.com/vmware-tanzu/vm-operator/api/v1alpha1
        alias: vmopv1

linters:
  disable-all: true
  enable:
  - asciicheck
  - bodyclose
  - depguard
  - dogsled
  - errcheck
  - exportloopref
  - goconst
  - gocritic
  - gocyclo
  - godot
  - gofmt
  - goimports
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - importas
  - ineffassign
  - misspell
  - nakedret
  - nilerr
  - nolintlint
  - prealloc
  - revive
  - rowserrcheck
  - staticcheck
  - stylecheck
  - typecheck
  - unconvert
  - unparam
  - unused

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  # Disable the default golangci exclusions so no issues are skipped. This will help reviewers to focus on
  # reviewing the most relevant changes in the PRs and avoid nitpicking.
  exclude-use-default: false
  exclude:
  # TODO: Remove the following exclusions over time once we have fixed those.
  - "ST1000: at least one file in a package should have a package comment"
  # List of regexps of issue texts to exclude, empty list by default.
  exclude-rules:
  - linters:
    - revive
    text: ".*should have (a package )?comment.*"
  - linters:
    - revive
    text: "^exported: comment on exported const"
  - linters:
    - gosec
    text: "G114: Use of net/http serve function that has no support for setting timeouts"
  # Dot imports for gomega or ginkgo are allowed within test files.
  - path: test/
    text: should not use dot imports
  # All of our webhooks follow the pattern of passing the webhook context which contains fields like the Client.
  # Ignore the linter warnings for now.
  - path: webhooks/
    text: ".* `ctx` is unused"
  - path: pkg/vmprovider/providers/vsphere/internal/internal.go
    text: ".*ST1003|don\'t use underscores in Go names.*"
